version: "2"

run:
  timeout: 5m
  tests: true

formatters:
  enable:
    - gofmt

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gocyclo
    - dupl
    - gosec
    - unconvert
    - goconst
    - gocognit

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  gocognit:
    min-complexity: 20
  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
