version: "2"

run:
  timeout: 5m
  tests: false
  skip-dirs:
    - tests

linters:
  default: none
  enable:
    - govet
    - misspell

linters-settings:
  govet:
    enable-all: false
    enable:
      - atomic
      - bools
      - composites
      - copylocks
      - nilfunc
      - printf
      - stdmethods
      - structtag

issues:
  exclude-rules:
    # Exclude known issues
    - path: internal/converter/encoding.go
      text: "ineffectual assignment"
