version: 2

project_name: repodocs

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: repodocs
    main: ./cmd/repodocs
    binary: repodocs
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/quantmind-br/repodocs-go/pkg/version.Version={{.Version}}
      - -X github.com/quantmind-br/repodocs-go/pkg/version.BuildTime={{.Date}}
      - -X github.com/quantmind-br/repodocs-go/pkg/version.Commit={{.ShortCommit}}

archives:
  - id: default
    formats:
      - tar.gz
      - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*
      - configs/config.yaml.template

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Documentation"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Other"
      order: 999
  filters:
    exclude:
      - "^chore:"
      - "^ci:"
      - "^style:"
      - "merge conflict"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: quantmind-br
    name: repodocs-go
  draft: false
  prerelease: auto
  mode: replace
  name_template: "v{{.Version}}"
  header: |
    ## repodocs v{{.Version}}
    
    Documentation extraction CLI tool.
  footer: |
    ## Installation
    
    ### Download Binary
    Download the appropriate binary for your platform from the assets below.
    
    ### From Source
    ```bash
    go install github.com/quantmind-br/repodocs-go/cmd/repodocs@v{{.Version}}
    ```
    
    ---
    **Full Changelog**: https://github.com/quantmind-br/repodocs-go/compare/{{.PreviousTag}}...{{.Tag}}
