version: 2

project_name: repodocs

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: repodocs
    main: ./cmd/repodocs
    binary: repodocs
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/quantmind-br/repodocs-go/pkg/version.Version={{.Version}}
      - -X github.com/quantmind-br/repodocs-go/pkg/version.BuildTime={{.Date}}
      - -X github.com/quantmind-br/repodocs-go/pkg/version.Commit={{.ShortCommit}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*
      - configs/config.yaml.template

nfpms:
  - id: packages
    package_name: repodocs
    vendor: Quantmind
    homepage: https://github.com/quantmind-br/repodocs-go
    maintainer: Quantmind <contact@quantmind.com>
    description: Documentation extraction CLI tool for LLMs
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: configs/config.yaml.template
        dst: /etc/repodocs/config.yaml.template
        type: config

brews:
  - name: repodocs
    repository:
      owner: quantmind-br
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/quantmind-br/repodocs-go
    description: Documentation extraction CLI tool for LLMs
    license: MIT
    skip_upload: auto
    install: |
      bin.install "repodocs"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Documentation"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Other"
      order: 999
  filters:
    exclude:
      - "^chore:"
      - "^ci:"
      - "^style:"
      - "merge conflict"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: quantmind-br
    name: repodocs-go
  draft: false
  prerelease: auto
  mode: replace
  name_template: "v{{.Version}}"
  header: |
    ## repodocs v{{.Version}}
    
    Documentation extraction CLI tool.
  footer: |
    ## Installation
    
    ### Linux (Debian/Ubuntu)
    ```bash
    sudo dpkg -i repodocs_{{.Version}}_linux_amd64.deb
    ```
    
    ### Linux (RPM)
    ```bash
    sudo rpm -i repodocs_{{.Version}}_linux_amd64.rpm
    ```
    
    ### macOS (Homebrew)
    ```bash
    brew install quantmind-br/tap/repodocs
    ```
    
    ### From Source
    ```bash
    go install github.com/quantmind-br/repodocs-go/cmd/repodocs@v{{.Version}}
    ```
    
    ---
    **Full Changelog**: https://github.com/quantmind-br/repodocs-go/compare/{{.PreviousTag}}...{{.Tag}}
